### ISSUE TITLE
A seperation of concerns: Moving Google Fonts scripts into its own repo

### ISSUE THREAD

**Issue by m4rc1e** [m4rc1e/mf-glyphs-scripts#26]
This repo currently has the following structure:
- Google Fonts
- Fixes
- QA
- Reports

I would like Google Fonts to have its own repo. The repo owner will be [googlefonts](https://github.com/googlefonts). The repo could be names googlefonts/glyphsscripts. We could then reference this much easier in our documentation.

I need to give this repository a major cleanup and write proper documentation using [readthedocs](https://readthedocs.org).

Thoughts @davelab6 @alexeiva?

**Comment by davelab6** [comment]
github.com/googlefonts/gf-glyphs-scripts sounds good

**Comment by davelab6** [comment]
Easiest thing is if you create a repo with that name I can fork it into /gf/

**Comment by m4rc1e** [comment]
I can actually make repos now in googlefonts :-)

I'm doing a refresh of these scripts with better documentation at the moment.

**Comment by m4rc1e** [comment]
It's been a while but its finally happened:
https://github.com/googlefonts/gf-glyphs-scripts

**Comment by davelab6** [comment]
Woop Woop!

**Comment by davelab6** [comment]
Woop Woop!

On Apr 24, 2017 9:51 AM, "Marc Foley" <notifications@github.com> wrote:

It's been a while but its finally happened:
https://github.com/googlefonts/gf-glyphs-scripts

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/m4rc1e/mf-glyphs-scripts/issues/26#issuecomment-296674716>,
or mute the thread
